name: Capstone3
channels:
  - defaults
dependencies:
  - aiofiles=22.1.0=py39haa95532_0
  - aiosqlite=0.18.0=py39haa95532_0
  - anyio=3.5.0=py39haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.1.0=py39haa95532_0
  - babel=2.11.0=py39haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py39haa95532_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli-python=1.0.9=py39hd77b12b_7
  - ca-certificates=2023.08.22=haa95532_0
  - certifi=2023.7.22=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py39haa95532_0
  - comm=0.1.2=py39haa95532_0
  - console_shortcut=0.1.1=4
  - cryptography=41.0.3=py39h89fc84f_0
  - debugpy=1.6.7=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39haa95532_0
  - exceptiongroup=1.0.4=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - idna=3.4=py39haa95532_0
  - importlib-metadata=6.0.0=py39haa95532_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - ipykernel=6.25.0=py39h9909e9c_0
  - ipython=8.15.0=py39haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py39haa95532_1
  - jinja2=3.1.2=py39haa95532_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py39haa95532_0
  - jupyter_client=7.4.9=py39haa95532_0
  - jupyter_core=5.5.0=py39haa95532_0
  - jupyter_events=0.6.3=py39haa95532_0
  - jupyter_server=1.23.4=py39haa95532_0
  - jupyter_server_fileid=0.9.0=py39haa95532_0
  - jupyter_server_ydoc=0.8.0=py39haa95532_1
  - jupyter_ydoc=0.2.4=py39haa95532_0
  - jupyterlab=3.6.3=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py39haa95532_0
  - libiconv=1.16=h2bbff1b_2
  - libsodium=1.0.18=h62dcd97_0
  - libxml2=2.10.4=h0ad7f3c_1
  - libxslt=1.1.37=h2bbff1b_1
  - lxml=4.9.3=py39h09808a7_0
  - markupsafe=2.1.1=py39h2bbff1b_0
  - matplotlib-inline=0.1.6=py39haa95532_0
  - mistune=0.8.4=py39h2bbff1b_1000
  - nbclassic=0.5.5=py39haa95532_0
  - nbclient=0.8.0=py39haa95532_0
  - nbconvert=6.5.4=py39haa95532_0
  - nbformat=5.9.2=py39haa95532_0
  - nest-asyncio=1.5.6=py39haa95532_0
  - notebook=6.5.4=py39haa95532_1
  - notebook-shim=0.2.2=py39haa95532_0
  - openssl=3.0.11=h2bbff1b_2
  - packaging=23.1=py39haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3=py39haa95532_0
  - platformdirs=3.10.0=py39haa95532_0
  - powershell_shortcut=0.0.1=3
  - prometheus_client=0.14.1=py39haa95532_0
  - prompt-toolkit=3.0.36=py39haa95532_0
  - psutil=5.9.0=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39haa95532_1
  - pyopenssl=23.2.0=py39haa95532_0
  - pyrsistent=0.18.0=py39h196d8e1_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.18=h1aa4202_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39haa95532_0
  - python-json-logger=2.0.7=py39haa95532_0
  - pytz=2023.3.post1=py39haa95532_0
  - pywin32=305=py39h2bbff1b_0
  - pywinpty=2.0.10=py39h5da7b33_0
  - pyyaml=6.0.1=py39h2bbff1b_0
  - pyzmq=23.2.0=py39hd77b12b_0
  - requests=2.31.0=py39haa95532_0
  - rfc3339-validator=0.1.4=py39haa95532_0
  - rfc3986-validator=0.1.1=py39haa95532_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py39haa95532_1
  - soupsieve=2.5=py39haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py39haa95532_0
  - tinycss2=1.2.1=py39haa95532_0
  - tomli=2.0.1=py39haa95532_0
  - tornado=6.3.3=py39h2bbff1b_0
  - traitlets=5.7.1=py39haa95532_0
  - typing-extensions=4.7.1=py39haa95532_0
  - typing_extensions=4.7.1=py39haa95532_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.18=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39haa95532_1
  - websocket-client=0.58.0=py39haa95532_4
  - wheel=0.41.2=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - winpty=0.4.3=4
  - y-py=0.5.9=py39hb6bf4ef_0
  - yaml=0.2.5=he774522_0
  - ypy-websocket=0.8.2=py39haa95532_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.11.0=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_0
prefix: C:\Users\logan\anaconda3\envs\Capstone3
